using Core.Exceptions;
using Core.Types;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Resources;
using System.Threading.Tasks;

namespace OpenDEVCore.OTP.Helpers
{
    public class ExMessages : ExceptionUtils<ExMessages>, IExMessages
    {
        public static string defaultExCode { get => "OTP999"; }
        static ResourceManager rm = new ResourceManager("OpenDEVCore.OTP.Resources.Resource", Assembly.GetExecutingAssembly());
        // Validaciones pre definidas para las entidades         
        public ResourceExDescription EntityValidationError { get => new ResourceExDescription("EFV001", "Validation error"); }
        public ResourceExDescription EntityDoesNotExists { get => new ResourceExDescription("BAS001", "The entity does not exist"); }
        public ResourceExDescription EntityAllreadyExists { get => new ResourceExDescription("BAS002", "Entity already exists"); }

        //Validation over Digital Bank
        public ResourceExDescription InstitutionNotExist { get => new ResourceExDescription("OTP001", "Institution Does Not Exist"); }
        public ResourceExDescription BadRequestOTP { get => new ResourceExDescription("OTP002", "The One Time Pin couldn't be generated by Bad Request - one or more incorrect properties"); }      

        public ResourceExDescription Map(CoreResponse coreResponse) => Map(new ExMessages(), defaultExCode, coreResponse);
    }
}
